/**
 * 
 */
import java.util.Random;
import java.util.Scanner;

import javax.swing.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.*;  

/**
 * @author Deyonta
 * 4/18/2019
 * Interactive GUI for registering college students
 *
 */

public class CollegeDatbase {
	

	/**
	 * @param args
	 * @throws SQLException 
	 * @throws IllegalAccessException 
	 * @throws InstantiationException 
	 * @throws ClassNotFoundException 
	 * @throws FileNotFoundException 
	 */
	public static void main(String[] args){
		// TODO Auto-generated method stub
		//JOptionPane.showMessageDialog(null, "Welcome to the SC College Student Information Database");
		JLabel title = new JLabel("Welcome to the SC College Student Information Database");
		title.setBounds(50, 10, 400, 30);
		
		//display the options for the user
		JFrame introFrame = new JFrame("SC College Student Information Database");
		JButton readFileOption = new JButton("Insert New Data from text file");
			readFileOption.setBounds(50, 50, 250, 30);
			readFileOption.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent arg0) {
					// TODO Auto-generated method stub
					try {
						insertDataFromFile();
					} catch (InstantiationException | IllegalAccessException | ClassNotFoundException
							| FileNotFoundException | SQLException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			} );
			
		JButton manuallyInsertInformation = new JButton("Manually Insert Student Data");
			manuallyInsertInformation.setBounds(50, 90, 250, 30);;
			manuallyInsertInformation.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
					try {
						insertInformation();
					} catch (InstantiationException | IllegalAccessException | ClassNotFoundException
							| FileNotFoundException | SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				}
				
			});
			
		JButton showStudentData = new JButton("Show All Student Data");
			showStudentData.setBounds(50, 130, 250, 30);
			showStudentData.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
					try {
						showAllData();
					} catch (InstantiationException | IllegalAccessException | ClassNotFoundException
							| FileNotFoundException | SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				}
				
			});
			
		introFrame.add(title);
		introFrame.add(readFileOption);
		introFrame.add(manuallyInsertInformation);
		introFrame.add(showStudentData);
		introFrame.setSize(500, 300);
		introFrame.setLayout(null);
		introFrame.setVisible(true);
		

	}//end of main

	public static String generateStudentID () {
		String ID = "";
		int rand = 0;
		//loop through and randomly select  a number
		//6x and convert it into a string
		for(int index = 0; index < 7; index++) {
			rand = (int)( Math.random() * 10);
			ID += String.valueOf(rand);
		}
		return ID;
	}
	
	public static String genereateEmail(String first, String middle, String last) {
		String email="";
		if(last.length() < 6){
			email = first.substring(0) + middle.substring(0) + last.substring(0, last.length()) + "@mit.edu";
		}else {
			email = first.substring(0) + middle.substring(0) + last.substring(0, 6) + "@mit.edu";
		}
		return email;
	}
	
	private static void insertDataFromFile() throws SQLException, InstantiationException, IllegalAccessException, 
	ClassNotFoundException, FileNotFoundException{
		// TODO Auto-generated method stub
		//connect to mysql database\
		Class.forName("com.mysql.jdbc.Driver");
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdata","root","Mydata123");  
		JOptionPane.showMessageDialog(null, "Connected to Database...");
		Statement statement = con.createStatement();
		
		JOptionPane.showMessageDialog(null, "Looking for txt file to enter info into database");
		//read file with the Student Information which should be the
		//first name, last name, middle initial, address,  major , minor, 
		//StudentID and email are generated by methods
		
		File inputFile = new File("src/info.txt");
		Scanner reader = new Scanner(inputFile);
		//JOptionPane.showMessageDialog(null, "got file about to print");

		while(reader.hasNext()) {
			String first = reader.next();
			String last = reader.next(); 
			String middle  = reader.next();
			String address = reader.next();
			String major = reader.next();
			String minor = reader.next();
			String id = generateStudentID();
			String email = genereateEmail(first, middle, last);
			JOptionPane.showMessageDialog(null, first + last + middle +"/n" + address + major + minor + id + email);
			String sql = "INSERT INTO studentinfo (firstName, lastName, address, major, minor, studentID, middleInitial, studentEmail) " + 
						 "VALUES (" +  "'"+first+"'" + ", " + "'"+last+"'" + ", " + "'"+address+"'" + ", " +  "'"+major+"'" + ", " 
								+ "'"+minor+"'" + ", " + "'"+id+"'" + ", " + "'"+middle+"'" + ", "+ "'"+email+"'"+ ")" + ";";
			JOptionPane.showMessageDialog(null,sql);
			statement.executeUpdate(sql);
		}
		con.close();
		statement.close();
		JOptionPane.showMessageDialog(null, "finished");
	}
	
	private static void insertInformation () throws SQLException, InstantiationException, IllegalAccessException, 
			ClassNotFoundException, FileNotFoundException{ 
		
		//create new window
		JFrame manuallyInsert = new JFrame("Manually Insert Student Information");
		JButton insertButton = new JButton("Insert");
			insertButton.setBounds(30, 220, 120, 20);
		JButton cancelButton = new JButton("Cancel");
			cancelButton.setBounds(160, 220, 120, 20);
			
		
		//firstName, lastName, address, major, minor, studentID, middleInitial, studentEmail
		//adding labels
		JLabel firstNameLabel = new JLabel("First Name : ");
			firstNameLabel.setBounds(30, 50, 90, 30);
			
		JLabel lastNameLabel = new JLabel("Last Name: ");
			lastNameLabel.setBounds(30, 70, 90, 30);
			
		JLabel milabel = new JLabel("M.I. :");
			milabel.setBounds(30, 90, 90, 30);
			
		JLabel addressLabel = new JLabel("Address : ");
			addressLabel.setBounds(30, 110, 90, 30);
			
		JLabel majorLabel = new JLabel("Major : ");
			majorLabel.setBounds(30, 130, 90, 30);
			
		JLabel minorLabel = new JLabel("Minor : ");
			minorLabel.setBounds(30, 150, 90, 30);
			
		JLabel studentIDLabel = new JLabel("StudentID : ");
			studentIDLabel.setBounds(30, 170, 90, 30);
			
		JLabel emailLabel = new JLabel("Email : ");
			emailLabel.setBounds(30, 190, 90, 30);
		
		//adding textfields
		JTextField firstNameTf = new JTextField();
			firstNameTf.setBounds(120, 55, 150, 20);
			
		JTextField lastNameTf = new JTextField();
			lastNameTf.setBounds(120, 75, 150, 20);
			
		JTextField miTf = new JTextField();
			miTf.setBounds(120, 95, 150, 20);
			
		JTextField addressTf = new JTextField();
			addressTf.setBounds(120, 115, 150, 20);
			
		JTextField majorTf = new JTextField();
			majorTf.setBounds(120, 135, 150, 20);
	
		JTextField minorTf = new JTextField();
			minorTf.setBounds(120, 155, 150, 20);
			
		JTextField studentIDTf = new JTextField();
			studentIDTf.setBounds(120, 175, 150, 20);
			
		JTextField emailTf = new JTextField();
			emailTf.setBounds(120, 195, 150, 20);
			
		/*
		 * ActionListener for the insert Button
		 * **/
		insertButton.addActionListener(new ActionListener(){
				@Override
				public void actionPerformed(ActionEvent e) {
					// TODO Auto-generated method stub
					try {
						Class.forName("com.mysql.jdbc.Driver");
						Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdata","root","Mydata123");
						Statement statement = con.createStatement();
						
						String first = firstNameTf.getText();
						String last = lastNameTf.getText();
						String middle  = miTf.getText();
						String address = addressTf.getText();
						String major = majorTf.getText();
						String minor = minorTf.getText();
						String id = studentIDTf.getText();
						String email = emailTf.getText();
						String sql = "INSERT INTO studentinfo (firstName, lastName, address, major, minor, studentID, middleInitial, studentEmail) " + 
								 "VALUES (" +  "'"+first+"'" + ", " + "'"+last+"'" + ", " + "'"+address+"'" + ", " +  "'"+major+"'" + ", " 
										+ "'"+minor+"'" + ", " + "'"+id+"'" + ", " + "'"+middle+"'" + ", "+ "'"+email+"'"+ ")" + ";";
						//JOptionPane.showMessageDialog(null,sql);
						
						statement.executeUpdate(sql);
						con.close();
						statement.close();
					} catch (ClassNotFoundException | SQLException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				}
			}); 
		
		manuallyInsert.add(firstNameLabel);
		manuallyInsert.add(lastNameLabel);
		manuallyInsert.add(milabel);
		manuallyInsert.add(addressLabel);
		manuallyInsert.add(majorLabel);
		manuallyInsert.add(minorLabel);
		manuallyInsert.add(studentIDLabel);
		manuallyInsert.add(emailLabel);
		
		manuallyInsert.add(insertButton);
		manuallyInsert.add(cancelButton);
		
		manuallyInsert.add(firstNameTf);
		manuallyInsert.add(lastNameTf);
		manuallyInsert.add(miTf);
		manuallyInsert.add(addressTf);
		manuallyInsert.add(majorTf);
		manuallyInsert.add(minorTf);
		manuallyInsert.add(studentIDTf);
		manuallyInsert.add(emailTf);
		
		manuallyInsert.setSize(400, 400);
		manuallyInsert.setLayout(null);
		manuallyInsert.setVisible(true);
	}
	
	private static void showAllData( ) throws SQLException, InstantiationException, IllegalAccessException, 
			ClassNotFoundException, FileNotFoundException {
		
		Class.forName("com.mysql.jdbc.Driver");
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdata","root","Mydata123");
		Statement statement = con.createStatement();
		String displayedText = "";
		String sql = "SELECT firstName, lastName, address, major, studentID, studentEmail FROM studentinfo" + ";";
		ResultSet rs = statement.executeQuery(sql);
		
		while(rs.next()) {
			
			//get the data
			String first = rs.getString("firstName");
			String last = rs.getString("lastName");
			String address = rs.getString("address");
			String major = rs.getString("major");
			String studentID = rs.getString("studentID");
			String email = rs.getString("studentEmail");
			
			displayedText += "\n";
			displayedText += "---------------------------------------------\n";
			displayedText += "Name :  " + first + " " + last + "\n" ;
			displayedText += "Address :  " + address + "\n";
			displayedText += "Major: " + major + "\n";
			displayedText += "Student ID: " + studentID + "\n";
			displayedText += "Email :  " + email + "\n";

		}
		
		//display the text
		JOptionPane.showMessageDialog(null, displayedText);
		
	}
	
}
